export default function Marketplace() {
  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-6">Idea Marketplace</h1>
      <p>Explore lessons generated by other users here.</p>
      {/* Add more content for the marketplace */}
    </div>
  );
}